# -*- coding: utf-8 -*-
__author__ = 'Palli'

class CodeOp:
    cd_LABEL = "LABEL"
    cd_UMINUS = "UMINUS"
    cd_ASSIGN = "ASSIGN"
    cd_ADD = "ADD"
    cd_SUB = "SUB"
    cd_MULT = "MULT"
    cd_DIVIDE = "DIVIDE"
    cd_DIV = "DIV"
    cd_MOD = "MOD"
    cd_OR = "OR"
    cd_AND = "AND"
    cd_NOT = "NOT"
    cd_LT = "LT"
    cd_LE = "LE"
    cd_GT = "GT"
    cd_GE = "GE"
    cd_EQ = "EQ"
    cd_NE = "NE"
    cd_GOTO = "GOTO"
    cd_CALL = "CALL"
    cd_APARAM = "APARAM"
    cd_FPARAM = "FPARAM"
    cd_VAR = "VAR"
    cd_RETURN = "RETURN"
    cd_NOOP = "NOOP"

class OpType:
    op_NONE = "NONE"
    op_EQ = "EQ"
    op_NE = "NE"
    op_LT = "LT"
    op_GT = "GT"
    op_GE = "GE"
    op_LE = "LE"
    op_MINUS = "MINUS"
    op_PLUS = "PLUS"
    op_OR = "OR"
    op_DIVIDE = "DIVIDE"
    op_DIV = "DIV"
    op_MULT = "MULT"
    op_AND = "AND"
    op_OR = "OR"
    op_MOD = "MOD"

class TokenCode:
    tc_PROGRAM = "PROGRAM"
    tc_VAR = "VAR"
    tc_ARRAY = "ARRAY"
    tc_OF = "OF"
    tc_INTEGER = "INTEGER"
    tc_REAL = "REAL"
    tc_FUNCTION = "FUNCTION"
    tc_PROCEDURE = "PROCEDURE"
    tc_BEGIN = "BEGIN"
    tc_END = "END"
    tc_IF = "IF"
    tc_THEN = "THEN"
    tc_ELSE = "ELSE"
    tc_WHILE = "WHILE"
    tc_DO = "DO"
    tc_NOT = "NOT"
    tc_COLON = "COLON"
    tc_SEMICOL = "SEMICOL"
    tc_COMMA = "COMMA"
    tc_DOTDOT = "DOTDOT"
    tc_DOT = "DOT"
    tc_LPAREN = "LPAREN"
    tc_LBRACK = "LBRACK"
    tc_RPAREN = "RPAREN"
    tc_RBRACK = "RBRACK"
    tc_NUMBER = "NUMBER"
    tc_RELOP = "RELOP"
    tc_ADDOP = "ADDOP"
    tc_MULOP = "MULOP"
    tc_ASSIGNOP = "ASSIGNOP"
    tc_ID = "ID"
    tc_COMMENT = "COMMENT"
    tc_NEWLINE = "NEWLINE"
    tc_ERROR = "ERROR"
    tc_ERROR = "ERROR2"
    tc_EOF = "EOF"

class DataType:
    dt_KEYWORD = "KEYWORD"
    dt_INTEGER = "INTEGER"
    dt_REAL = "REAL"
    dt_OP = "OP"
    dt_ID = "ID"
    dt_NONE = "NONE"