__author__ = 'palleymundsson'

op_NONE = "NONE"
op_EQ = "EQ"
op_NE = "NE"
op_LT = "LT"
op_GT = "GT"
op_LE = "LE"
op_GE = "GE"
op_PLUS = "PLUS"
op_MINUS = "MINUS"
op_OR = "OR"
op_MULT = "MULT"
op_DIVIDE = "DIVIDE"
op_DIV = "DIV"
op_MOD = "MOD"
op_AND = "AND"